Feature - WhiteLabelling
fooplugins/foogallery pull request #181
Opened 2021-06-05 00:02 UTC by oleg-shumar

Feature - WhiteLabelling

2021-06-05 06:20 UTC, bradvin commented
@oleg-shumar as a start, pls rename all mentions of "custom-branding" to "whitelabelling". This includes directory names, file names and variable names

2021-06-05 06:37 UTC, bradvin requested changes
Suggested a few changes with inline comments.
The main change is to rename all mentions of "custom branding" to "whitelabelling"

2021-06-05 06:37 UTC, bradvin commented on includes/extensions/class-extensions-api.php
> +
The whitelabelling extension should not be added here. The main reason is because it is always added even for free version. We want to only add the extension if the pro code is running. 

Rather introduce a new filter, eg. $this->extensions = apply_filters( 'foogallery_extensions', $this->extensions );

Which you can hook into and add the extension as you have done

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +	class Custom_Branding_FooGallery_Extension extends Foo_Plugin_Base_v2_4 {
This class does not need to extend Foo_Plugin_Base_v2_4. That was only done because it used to be a separate plugin. But now it will be part of the main plugin

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +	define( 'CUSTOM_BRANDING_FOOGALLERY_EXTENSION_UPDATE_URL', 'http://fooplugins.com/api/foogallery-branding/check' );
CUSTOM_BRANDING_FOOGALLERY_EXTENSION_UPDATE_URL is no longer needed, as the code is no longer part of a separate plugin which had its own licensing system.

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +	define( 'CUSTOM_BRANDING_FOOGALLERY_EXTENSION_VERSION', '1.0.1' );
Version no longer needed as the plugin is now part of base plugin

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +			$this->init( __FILE__, FOOGALLERY_SLUG, CUSTOM_BRANDING_FOOGALLERY_EXTENSION_VERSION, 'FooGallery Custom Branding' );
not needed

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +			$this->load_plugin_textdomain();
not needed

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +				add_filter( CUSTOM_BRANDING_FOOGALLERY_EXTENSION_SLUG . '_admin_settings', array($this, 'create_settings'), 10, 2 );
this should change back to 'foogallery_admin_settings'

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +			return $this->get_setting( 'custom_branding_name', $default );
all calls to $this->get_setting can be changed to foogallery_get_setting

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +		function get_setting( $key, $default = '' ) {
can be removed, if all calls are changed to foogallery_get_setting function

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +			$settings[] = array(
no longer needed, as FooBot image is not used anymore

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +			$settings[] = array(
can be removed - build you own tab no longer exists

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +			$settings[] = array(
can be removed - there is no longer an extensions section on help page

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +		function import_export_settings( $args ) {
can be removed - no license required

2021-06-05 06:37 UTC, bradvin commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +		function foogallery_version_check() {
This can also be removed, as it will be bundled in the plugin and will not be separate

2021-06-07 13:57 UTC, bradvin requested changes

2021-06-07 13:57 UTC, bradvin commented on includes/extensions/class-extensions-api.php
>  			$this->extensions[] = array(
adding the whitelabelling extension to the array should not be done within this file. It should be moved to foogallery-whitelabelling-extension.php

In that file, you can hook into **foogallery_available_extensions** filter

2021-06-07 13:57 UTC, bradvin commented on includes/foopluginbase/classes/class-foo-plugin-base.php
> -            $whitelabelling_settings = apply_filters( CUSTOM_BRANDING_FOOGALLERY_EXTENSION_SLUG . '_admin_settings', false );
This code should be removed from this file. The correct way to add settings is to hook into the **foogallery_admin_settings** filter.

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  		function alter_extension_categories( $categories ) {
not needed - can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
> -			$override = $this->foogallery_instance->options()->get( 'custom_branding_extensions_endpoint', $default );
all calls to **$this->foogallery_instance->options()->get** can be replaced with **foogallery_get_setting**

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  		function change_extensions_endpoint( $default ) {
change_extensions_endpoint function not needed and can be dropped

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
> -				add_filter( CUSTOM_BRANDING_FOOGALLERY_EXTENSION_SLUG . '_admin_settings', array($this, 'create_settings'), 10, 2 );
should be hooking into **foogallery_admin_settings** filter, not a custom filter

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
> +			$override = $this->foogallery_instance->options()->get( 'whitelabelling_extensions_endpoint', $default );
This function is not needed and can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  		function admin_help_title( $default ) {
this function is no longer used. Can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  		function admin_help_tagline( $default ) {
also can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  		function admin_help_tagline_link( $default ) {
also can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  		function admin_help_show_extensions_section() {
can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  		function admin_extensions_tagline( $default ) {
can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  			$settings[] = array(
no longer used. Can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  			$settings[] = array(
no longer needed. Can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  			$settings[] = array(
no longer needed. Can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  			$settings[] = array(
no longer needed. Can be removed

2021-06-07 13:57 UTC, bradvin commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  			$settings[] = array(
no longer needed. Can be removed

2021-06-09 07:01 UTC, oleg-shumar commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
> -			$override = $this->foogallery_instance->options()->get( 'custom_branding_extensions_endpoint', $default );
Pushed

2021-06-09 07:12 UTC, oleg-shumar commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  			$settings[] = array(
Pushed

2021-06-09 07:12 UTC, oleg-shumar commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  			$settings[] = array(
Pushed

2021-06-09 07:13 UTC, oleg-shumar commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  			$settings[] = array(
Pushed

2021-06-09 07:13 UTC, oleg-shumar commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  			$settings[] = array(
Pushed

2021-06-09 07:17 UTC, oleg-shumar commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  			$settings[] = array(
Pushed

2021-06-09 07:20 UTC, oleg-shumar commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  		function change_extensions_endpoint( $default ) {
Pushed

2021-06-09 07:21 UTC, oleg-shumar commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
>  		function alter_extension_categories( $categories ) {
Pushed

2021-06-09 07:23 UTC, oleg-shumar commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +		function get_setting( $key, $default = '' ) {
Pushed

2021-06-09 07:23 UTC, oleg-shumar commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +			return $this->get_setting( 'custom_branding_name', $default );
Pushed

2021-06-09 07:24 UTC, oleg-shumar commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +				add_filter( CUSTOM_BRANDING_FOOGALLERY_EXTENSION_SLUG . '_admin_settings', array($this, 'create_settings'), 10, 2 );
Pushed

2021-06-09 07:24 UTC, oleg-shumar commented on pro/extensions/custom-branding/foogallery-custom-branding-extension.php
> +			$this->load_plugin_textdomain();
Pushed

2021-06-09 07:25 UTC, oleg-shumar commented on pro/extensions/whitelabelling/foogallery-whitelabelling-extension.php
> +			$override = $this->foogallery_instance->options()->get( 'whitelabelling_extensions_endpoint', $default );
Pushed

2021-06-09 07:45 UTC, oleg-shumar commented on includes/extensions/class-extensions-api.php
>  			$this->extensions[] = array(
Pushed

2021-06-09 07:59 UTC, oleg-shumar commented on includes/foopluginbase/classes/class-foo-plugin-base.php
> -            $whitelabelling_settings = apply_filters( CUSTOM_BRANDING_FOOGALLERY_EXTENSION_SLUG . '_admin_settings', false );
Pushed

2021-06-09 18:50 UTC, merged